### ISSUE TITLE
Support for IE11 and Edge

### ISSUE THREAD

**Issue by Ximore** [matt3224/sapper-start#2] opened 2019-06-29 09:52 UTC
**Feature Request**
As IE11 _(despite being a legacy browser)_ still is widely used, especially at government institutions and some bigger organisations, and Edge is here to stay, it would be nice to have support for IE11 and Edge implemented by default. 

Looking at this repo: https://github.com/antony/sapper-ie, the additions needed seem somehow straight forward.. I know that Antony currently is evaluating a pull request that may improve it, so I will keep an eye out.

**Comment by matt3224** [comment] 2019-10-20 20:49
Apologies for the delay I somehow missed this. It's a shame browser list can't tell babel to add this stuff, i'm unsure if i'll get to to implement something and test it. Fee free to PR if you have time

**Comment by antony** [comment] 2019-11-01 00:32
@Ximore I'm not evaluating the PR - I think we decided that it works as is and the core-js version would just increase the bundle size in browsers that don't need it.

**Comment by CorfitzMe** [comment] 2019-11-01 07:59
I thought that was the reason for using Polyfills?

**Comment by matt3224** [comment] 2019-12-08 08:18
@Ximore I am going to close this as there is very little movement in the discussion. If you hit a specific bug that's IE11 related, open an issue for it and i'll do my best to reproduce and resolve 😇

**Closed by matt3224** 2019-12-08 08:18 UTC
